# Generated by Django 6.0.8 on 2026-08-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
