# Generated by Django 6.0.8 on 2026-08-11 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_ridestatus_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rides",
                to="accounts.vehicletype",
            ),
        ),
    ]
