# Generated by Django 6.0.8 on 2026-08-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_profile_user"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["rider", "created_at"], name="accounts_ri_rider_i_90987c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["driver", "created_at"], name="accounts_ri_driver__cb034e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["status", "created_at"], name="accounts_ri_status__583373_idx"
            ),
        ),
    ]
