# Generated by Django 6.0.8 on 2026-08-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_ride_accounts_ri_rider_i_90987c_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="driverprofile",
            index=models.Index(
                fields=["status", "created_at"], name="accounts_dr_status_7f2069_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_deleted"], name="accounts_pr_is_dele_f49be4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["vehicle_type"], name="accounts_ri_vehicle_3661ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["vehicle_type", "created_at"],
                name="accounts_ri_vehicle_24a07a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["driver", "vehicle_type"], name="accounts_ve_driver__fe20ce_idx"
            ),
        ),
    ]
