# Generated by Django 6.0.8 on 2026-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_driverlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlocation",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("busy", "Busy"),
                ],
                default="offline",
                max_length=20,
            ),
        ),
    ]
