# Generated by Django 6.0.8 on 2026-08-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="Notification", max_length=255),
        ),
    ]
