# Generated by Django 6.0.8 on 2026-09-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_notification_title"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="accounts_no_user_id_501ff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="accounts_no_user_id_a4ff2e_idx"
            ),
        ),
    ]
