# Generated by Django 6.0.8 on 2026-09-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_notification_accounts_no_user_id_501ff2_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="base_fare",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="cost_per_km",
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="cost_per_minute",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
    ]
