# Generated by Django 6.0.8 on 2026-09-22 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_booking_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="service",
            name="accounts_se_name_689853_idx",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="accounts_se_status_d0c955_idx",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="accounts_se_categor_b44595_idx",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="accounts_se_provide_315007_idx",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="accounts_se_status_a03d49_idx",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="description",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="status",
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="accounts.booking",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="provider_profiles/"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="duration",
            field=models.PositiveIntegerField(
                default=60, help_text="Duration in minutes"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ride_requested", "Ride Requested"),
                    ("ride_accepted", "Ride Accepted"),
                    ("driver_arriving", "Driver Arriving"),
                    ("ride_started", "Ride Started"),
                    ("ride_completed", "Ride Completed"),
                    ("ride_cancelled", "Ride Cancelled"),
                    ("booking_created", "Booking Created"),
                    ("payment_successful", "Payment Successful"),
                    ("booking_confirmed", "Booking Confirmed"),
                    ("provider_started", "Provider Started Service"),
                    ("booking_completed", "Booking Completed"),
                    ("booking_cancelled", "Booking Cancelled"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="ride",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="accounts.ride",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("user", "booking", "notification_type"),
                name="unique_booking_notification",
            ),
        ),
        migrations.RemoveField(
            model_name="service",
            name="category",
        ),
        migrations.RemoveField(
            model_name="service",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="service",
            name="status",
        ),
    ]
