# Generated by Django 6.0.8 on 2026-09-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_serviceimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("booking", "idempotency_key"),
                name="unique_booking_idempotency_key",
            ),
        ),
    ]
