# Generated by Django 6.0.8 on 2026-10-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_savedservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ride_requested", "Ride Requested"),
                    ("ride_accepted", "Ride Accepted"),
                    ("driver_arriving", "Driver Arriving"),
                    ("ride_started", "Ride Started"),
                    ("ride_completed", "Ride Completed"),
                    ("ride_cancelled", "Ride Cancelled"),
                    ("booking_created", "Booking Created"),
                    ("payment_successful", "Payment Successful"),
                    ("booking_confirmed", "Booking Confirmed"),
                    ("provider_started", "Provider Started Service"),
                    ("booking_completed", "Booking Completed"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("saved_service_unavailable", "Saved Service Unavailable"),
                ],
                max_length=30,
            ),
        ),
    ]
