RIDE_ACTIVE_STATUSES = [
    "REQUESTED",
    "ACCEPTED",
    "DRIVER_ARRIVING",
    "STARTED",
]

RIDE_COMPLETED_STATUS = "COMPLETED"

RIDE_CANCELLED_STATUS = "CANCELLED"

DEFAULT_CACHE_TIMEOUT = 60

DEFAULT_PAGE_SIZE = 10

MAX_PAGE_SIZE = 50
