name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

      DB_NAME: mydb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: 127.0.0.1
      DB_PORT: 5432

      REDIS_URL: redis://127.0.0.1:6379/0
      CELERY_BROKER_URL: redis://127.0.0.1:6379/0
      CELERY_RESULT_BACKEND: redis://127.0.0.1:6379/1
      REDIS_CACHE_URL: redis://127.0.0.1:6379/1

      JWT_ACCESS_TOKEN_MINUTES: ${{ secrets.JWT_ACCESS_TOKEN_MINUTES }}
      JWT_REFRESH_TOKEN_DAYS: ${{ secrets.JWT_REFRESH_TOKEN_DAYS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install linting tool
        run: |
          pip install flake8

      - name: Django system check
        run: |
          python manage.py check

      - name: Run migrations
        run: |
          python manage.py migrate --noinput

      - name: Check migrations
        run: |
          python manage.py migrate --check

      - name: Run tests
        run: |
          python manage.py test

      - name: Run linting
        run: |
          flake8 .

      - name: Build Docker image
        run: |
          docker build -t django-ride-booking:ci .